"""upate relation between movies and actors to many to many

Revision ID: 0d9a7fde0b9c
Revises: 1c60d2a18076
Create Date: 2020-07-19 00:03:11.404900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9a7fde0b9c'
down_revision = '1c60d2a18076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actors_movie_id_fkey', 'actors', type_='foreignkey')
    op.drop_column('actors', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('actors_movie_id_fkey', 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
